### PR TITLE
Default Keyword Replacement Mapping Feature

### LINKED ISSUE #43: Writing multiple client or resource servers to same local configuration
### Describe the problem you'd like to have solved

Given the following `environment.json` clients configuration

```json
{
  "name": "Sample",
  "version": "1.0.0",
  "resources": "../../src/tenant/tenant.yaml",
  "clients": [
    {
      "name": "ExampleWebApp",
      "directory": "src/web-app",
      "env": {
        "AUDIENCE": "http://api.com/api",
        "API_URL": "ImpersonationAPI",
        "BASE_URL": "ExampleWebAppUsingImpersonation",
        "ISSUER_BASE_URL": "$tenant_base_url",
        "CLIENT_ID": "$client_id",
        "CLIENT_SECRET": "$client_secret",
        "SECRET": "a long, randomly-generated string stored in env",
        "PORT": 37500
      }
    },
    {
      "name": "ExampleWebAppMiddleware",
      "directory": "src/web-app",
      "env": {
        "IMP_CLIENT_ID":"$client_id",
        "IMP_CLIENT_SECRET":"$client_secret",
        "IMP_AUDIENCE":"https://example.com/impersonate"
      }
```
**Note:** Both client registrations write .env values to the same directory.

When the `auth0.lab.localConfigure` command is executed the extension will write the .env values for the ExampleWebApp and then overwrite those .env values with the ExampleWebAppMiddleware.

### Describe the ideal solution

In this case the application found in `src/web-app` uses one client registration to perform standard authentication, but uses middleware that requires a separate client registration for a specific purpose and has limited scopes.

When two or more registrations exist for the same .env file, the extension should append to the file instead of overwriting it.

## Alternatives and current work-arounds

There are not current workarounds for this situation.

### Additional context

The current implementation is found in writer.ts.

```typescript
writeAll = async (resolvers: Resolver[]) => {
    resolvers.forEach(async (resolver) => {
      const uri = vscode.Uri.joinPath(this.worspace, resolver.getDirectory(),  '.env');

      const env = 
        resolver
          .resolveEnv(resolvers)
          .map((i) => `${i.name}=${i.value}`)
          .join('\n');

      await fs.writeFile(uri, Buffer.from(env, 'utf8'));
    });
  };
```

This method could be updated to read any existing values from the .env file, concat them with the new values, filter for duplicates and then write a new file.

### LINKED ISSUE #44: Post Configuration Script
### Describe the problem you'd like to have solved

Given I have an extensibility script that uses a client registration's client id and secret
When I configure a sample application using the VSCode Extension
Then I would like a way to execute a script to store the secret values on completion of configuration

### Describe the ideal solution

Currently, resources are defined in the environment.json file like so:

```json
{
  "name": "Impersonation: Custom DB",
  "version": "1.0.0",
  "resources": "../../src/tenant/tenant.yaml",
  "clients": [
    {
      "name": "ExampleWebApp",
      "directory": "src/web-app",
      "env": {
        "ISSUER_BASE_URL": "$tenant_base_url",
        "CLIENT_ID": "$client_id",
        "CLIENT_SECRET": "$client_secret",
        "SECRET": "a long, randomly-generated string stored in env",
        "PORT": 37500
      }
    }
  ]
}
```

It could be updated like so:

```json
{
  "name": "Impersonation: Custom DB",
  "version": "1.0.0",
  "resources": "../../src/tenant/tenant.yaml",
  "postConfigureCommand": "../../src/tenant/apply-secrets.sh",
  "clients": [
    {
      "name": "ExampleWebApp",
      "directory": "src/web-app",
      "env": {
        "ISSUER_BASE_URL": "$tenant_base_url",
        "CLIENT_ID": "$client_id",
        "CLIENT_SECRET": "$client_secret",
        "SECRET": "a long, randomly-generated string stored in env",
        "PORT": 37500
      }
    }
  ]
}
```

This command should be executed as a third step in the `configureLab` [method](https://github.com/auth0-training/labs-vscode-extension/blob/main/src/features/labs/commands.ts#L98) and be available as a stand alone command.

The script should be run with access to environment variables for `AUTH0_DOMAIN` and `AUTH0_TOKEN` defined giving the script the ability to interact with the management API. The script is free to fetch values using the local .env files as well.

### LINKED ISSUE #45: Runtime specific replacement values for tenant configuration
### Description

Given the following tenant.yml configuration:

```yml
clients:
  - name: ExampleWebApp
    app_type: regular_web
    allowed_logout_urls:
      - http://localhost:3000
      - https://##CODESPACE_NAME##-37500.preview.app.github.dev
    callbacks:
      - http://localhost:3000/callback
      - https://##CODESPACE_NAME##-37500.preview.app.github.dev/callback
clientGrants:
  - client_id: ExampleWebApp
    audience: https://##AUTH0_DOMAIN##/api/v2/
    scope:
      - read:users
```

When a user attempts to configure a lab, the deployment will fail for these reasons:

1. `CODESPACE_NAME` is not available as a keyword replacement and will cause an invalid entry to be written to the tenant application registration
2. `AUTH0_DOMAIN` is not available as a keyword replacement and will cause an error to be generated attempting to write the client grants to the management api registration for the tenant.

These values are available at runtime to the extension and can be passed as default values so these substitutions work correctly.

### Describe the ideal solution

These values should be provided as default replacement values during tenant configuration deployment.

### PR DESCRIPTION
**Pull request by NotMyself**
### Description

This PR addresses a number of feature requests for running samples in GitHub Codespaces and advanced configuration use cases.

Fixes #45
Fixes #44 
Fixes #43 

### Testing

To test this change, you will need to run a lab in codespaces with a custom build of the extension.

1. open a lab repository in codespaces.
2. uninstall the auth0 labs extension from the running codespace
3. download the custom build associated with the pull request
4. uncompress the zip archive to gain access to the release.vsix file
5. on the extension pane, select the `...` menu and select **Install from VSIX**
6. click the show local button
7. select the release.vsix

You now have a custom install of the extension running in codespaces. 

#### Default Keyword Replacement Mapping

Update the tenant.yml for the lab to include the keyword replacements for `AUTH0_DOMAIN` and `CODESPACE_NAME`. Sign in to a tenant and click the configure button when prompted.

The deploy should be successful and you should see the appropriate values in your tenant and associated .env files.

#### Post Configuration Script

Update the environment.json for the lab to include a reference to a shell script. Create the shell script and echo out the values for `AUTH0_DOMAIN` and `AUTH0_TOKEN`.

Run the configure command and verify values are printed to console output.

#### Multiple Writes to Same .env File

Update the environment.josn for the lab to write two or more clients to the same directory.

Run the configure command and verify that all values are written to the .env file with no duplication.

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not `master`

### CODE REVIEW

**Comment by jesposito** [comment]
I've tested and everything appears to work well. I think we should wait and have Sara do a run-through as well just to be certain. Thanks Bobby!

**Comment by NotMyself** [comment]
That works for me. I have not done the release prep yet. Maybe @kazemicode can do it once she has reviewed for the practice on releasing.

**Comment by kazemicode** [comment]
@NotMyself Tested and can confirm the fixes for #45 works as expected. 

For #43, it only works as expected if there's already existing data in `.env` to append to. However, if you are starting fresh and there are two app configs in `environment.json`, the first app's variables seem to get overwritten by the second. If I rerun the config, then I see the first app's variables get appended after the second app's in the `.env`.

Regarding #44,  I don't see any evidence of the shell script executing after creating one and adding the path to `postConfigureCommand` in `environment.json`. This was tested in both Codespaces and locally. When I manually executed my shell script (in Codespaces I had to chmod +x first), there didn't seem to be values for `$AUTH0_TENANT` or `$AUTH0_TOKEN`, but `$CODESPACE_NAME` existed.

**Comment by NotMyself** [comment]
@kazemicode thanks for the review! While I was waiting for the first fix to get approved... I was implementing fixes for other things... So #43 should be working now and I am working on #44 right now. I'll let you know when they are ready.

**Comment by NotMyself** [comment]
@jesposito @kazemicode all three fixes are now in. We have verified they work for us in our use case. Just need confirmation that we didn't break labs... and you all approve. Then we can ship a new version with killer new features.

**Review by kazemicode — APPROVED** [review]
Tested and confirmed the changes fix #43 #44 and #45 without introducing bugs to existing labs.

**Pull request merged**
